Models/ErrorViewModel.cs
using System;

namespace COPC_Wiki.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/GraphQuery.cs
using System;
using GraphQL;


namespace COPC_Wiki.Models
{

    public class GraphQuery
    {
        
        private static  GraphQuery instance = null;
       
        private static readonly object padlock = new object();
        
        private GraphQuery()
        {

        }

        public static GraphQuery Instance()
        {
            lock (padlock)
            {
                if(instance == null)
                {
                    instance = new GraphQuery();
                }
                return instance;
            }
            
        }

        public GraphQLRequest getDepartments()
        {

            var departmentRequest = new GraphQLRequest
            {
                Query = @"
                    query{
                        departments
                        {
                            id
                            Name
                            subjects{
                                id
                                Title
                                articles
                                {
                                    id
                                    Title
                                }
                            }
                        }
                    }
                "
                
            };
            return departmentRequest;
        }


        public GraphQLRequest getDepartmentById(int _id)
        {

            string _query = @"query {department(id: ";
            string _querystring = _query + _id + @" ) 
            {
                id
                Name
                subjects
                {
                    id
                    Title
                    articles
                    {
                        id
                        Title
                        content
                    }
                }
             
              }
            }";
            var departmentRequest = new GraphQLRequest
            {
                Query = _querystring
                
            };
           

            return departmentRequest;
        }

         public GraphQLRequest getArticleById(string Slug)
         {
            
            var Request = new GraphQLRequest
            {
                Query = @"query getArticle($_Slug: String)
                {
                    wikiArticles(where: {Slug : $_Slug})
                    {
                        id
                        Title
                        Slug
                        Content
                    }
                }", 
                OperationName = "getArticle",
                Variables = new {
                    _Slug = Slug
                }
                
            };
            return Request;
            
         }

        public GraphQLRequest getWikiPages()
        {
            var wikiRequest = new GraphQLRequest
            {
                Query = @"
                    query{
                        wikiPages{
                            id
                            Topic
                            Slug
                            Subheading
                            {
                                 ... on ComponentWikiNavigation
                                {
                                    id
                                    Topic
                                    Articles
                                    {
                                        id
                                        Slug
                                        Title
                                        Content
                                    }
                                } 
                            }
                        }
                    }
                "
                

                
            };
            
            return wikiRequest;
        }

    }

    

}

Models/WikiPages.cs
using System;
using System.Collections.Generic;

namespace COPC_Wiki.Models{

    public class WikiPages 
    {
        public wikiPages[] wikiPages {get; set;}
    }
    public class wikiPages
    {
        public int Id {get; set;}
            
        public string Topic {get; set;}

        public string Slug {get; set;}

        public DateTime published_at {get; set;}

        public DateTime created_at {get; set;}

        public DateTime updated_at {get; set;}

        public Subsection[] Subheading{get; set;}
    }
    public class Subsection
    {
        public int Id {get; set;}
        public string Topic {get; set;}
        public Article[] Articles {get; set;}

    }
    public class Articles
    {
        public Article wikiArticle {get;set;}
        public Article[] wikiArticles {get;set;}       
    }
    public class Article
    {
        public int Id {get; set;}
        public string Slug {get; set;}
        public string Title {get; set;}
        public string content {get; set;}
    }
}

Controllers/Components/NavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System;
using System.Threading.Tasks;
using System.Net.Http;
using System.Net.Http.Json;
using GraphQL.Client.Http;
using GraphQL.Client.Serializer.Newtonsoft;
using GraphQL;
using System.Linq;
using System.Text.Json;

namespace COPC_Wiki.Controllers
{

 public class NavigationViewComponent : ViewComponent
    {
        //string Baseurl = "https://dev.manage.palmcoast.gov/graphql";
        string Baseurl = "http://localhost:7331/graphql";
        COPC_Wiki.Models.GraphQuery query = COPC_Wiki.Models.GraphQuery.Instance();

        public async Task<IViewComponentResult> InvokeAsync()
        {
            
            using var graphQLClient = new GraphQLHttpClient(Baseurl, new NewtonsoftJsonSerializer());

            var graphQLResponse = await graphQLClient.SendQueryAsync<COPC_Wiki.Models.WikiPages>(query.getWikiPages());
           
            //Console.WriteLine("raw response:");
            //Console.WriteLine(JsonSerializer.Serialize(graphQLResponse, new JsonSerializerOptions { WriteIndented = true }));
            return View("Navigation" , graphQLResponse.Data);
        }
    }

}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using COPC_Wiki.Models;
using GraphQL.Client.Http;
using GraphQL.Client.Serializer.Newtonsoft;
using GraphQL;
using System.Text.Json;


namespace COPC_Wiki.Controllers
{
    public class HomeController : Controller
    {
        private string Baseurl = "http://localhost:7331/graphql";
        GraphQuery query = GraphQuery.Instance();

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public async Task<ActionResult> Article(string SlugQuery)
        {
            using var graphQLClient = new GraphQLHttpClient(Baseurl, new NewtonsoftJsonSerializer());

            var graphQLResponse = await graphQLClient.SendQueryAsync<Models.Articles>(query.getArticleById(SlugQuery));

          
            //Console.WriteLine(SlugQuery);
            //Console.WriteLine("raw response:");
            //Console.WriteLine(JsonSerializer.Serialize(graphQLResponse, new JsonSerializerOptions { WriteIndented = true }));
            
            return View(graphQLResponse.Data);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Home/Article.cshtml
@model COPC_Wiki.Models.Articles

<div class="container">
    <div class="contentbody">@Html.Raw(@Model.wikiArticles[0].content)</div>
 <style>
     
    .WikiPage  .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100%;
        
    }
    .WikiPage .container .p {
        text-transform: uppercase;
        font-weight: bold;
        font-size: 2.5em;


    }
    .WikiPage .container .contentbody p img
    {
        width: 60%;
        position: relative;
        display: block;
        margin-left: auto;
        margin-right: auto;
    }
    .contentbody
    {
        padding-top: 5% !important;
        height: 100%;
        color: black;
        text-shadow:10px 10px 10px rgba(0,0,0,.3);
        width: inherit;
    }
    .WikiPage  a {
        position: relative;
    }
    
    .WikiPage  p 
    {
        text-transform: uppercase;
        font-size: 1em;
        letter-spacing: 0.1em;
        font-weight: bold;
        margin-top: 20px;
    }

 </style>

</div>

Views/Home/Index.cshtml
<div class="container">
    <p>City of Palm Coast Wiki Pages</p>
 <style>
     .WikiPage
     {
         background-image: url('../images/Palm.jpg');
         background-size: cover;
     }
   
   .WikiPage  .container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 100%;
        
        padding: 0px !important;
        
        
    }
    .WikiPage .container .p {
        text-transform: uppercase;
        font-weight: bold;
        font-size: 2.5em;

    }
    .WikiPage  a {
        position: relative;
    }
    .WikiPage  a img {
        width: 480px;
        height: 520px;
    }
    .WikiPage  p 
    {
        text-transform: uppercase;
        font-size: 2.2em;
        letter-spacing: 0.1em;
        color: #d119ff;
        font-weight: bold;
        margin-top: 20px;
        font-family: 'Roboto';
        text-shadow:10px 10px 10px rgba(0,0,0,.4);
        position: absolute;
        left: 100px;
        up: 20%;
    }

    @@media only screen and (max-width: 600px)
    {
        .WikiPage  p 
        {
            font-size: 1.5em;
        }
    } 

 </style>
</div>

Views/Shared/Components/Navigation/Navigation.cshtml
@model COPC_Wiki.Models.WikiPages
<body>
    <nav class="nav">
      <ul>
        <li class="active">
            <a asp-area="" asp-controller="Home" asp-action="Index">Welcome</a>
        </li>
        @foreach (var m in Model.wikiPages)
        {
            <li>
                <a href="#@m.Slug" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">@m.Topic</a>
                <ul class="collapse list-unstyled" id="@m.Slug">
                    @if(@m.Subheading != null)
                    {
                        @foreach (var sub in @m.Subheading)
                        {

                            <a href="#Subhead_@sub.Id" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">@sub.Topic</a>
                            <ul class="collapse list-unstyled" id="Subhead_@sub.Id">
                                @if (@sub.Articles != null)
                                {
                                    @foreach (var article in @sub.Articles)
                                    {
                                        <li>
                                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Article" asp-route-SlugQuery=@article.Slug>@article.Title</a>
                                        </li>
                                        
                                    }
                                }
                            </ul>
                        }
                    }
                </ul>
            </li>
        }
      </ul>
    </nav>
    <style>
        nav {
            position: relative;
            margin: 0 15%;
            text-align: left;
            top: 50%;
            transform: translateY(-50%);
            font-weight: bold;
            max-height: inherit;
            padding-top: 15% !important;
            display: flex;
            

        }
        .nav ul {
            list-style: none;
            padding: 0px !important;
            
            
        }
        .nav ul li {
            position: relative;
            margin: 3.2em 0;
            
        }
        .nav ul ul ul li
        {
            margin: 0.4em 0;
        }
        .nav ul li a {
            line-height: 5em;
            text-transform: uppercase;
            text-decoration: none;
            letter-spacing: 0.4em;
            color: rgba(255, 255, 255, 0.35);
            display: block;
            transition: all ease-out 300ms;
            font-size: 1.5em;
            
        }
        .nav ul li.active a {
            color: white;
        }
        .nav ul li:not(.active)::after {
            opacity: 0.2;
            
        }
        .nav ul li:not(.active):hover a {
            color: rgba(255, 255, 255, 0.75);
        }
        .nav ul li::after {
            content: "";
            position: absolute;
            width: 100%;
            height: 0.2em;
            background: black;
            left: 0;
            bottom: 0;
            background-image: linear-gradient(to right, #5e42a6, #b74e91);
        }
        .dropdown-toggle::after {
            display:none;
        }
        ul ul a {
            font-size: 1.0em !important;
            padding-left: 50px;
            
        }
        
        ul ul ul a {
            font-size: 0.8em !important;
            margin-left: 20px !important;
            padding-left: 75px !important;
        }
        
    </style>
</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - COPC_Wiki</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans">
</head>
<main class="main">
  <aside class="sidebar">
    @await Component.InvokeAsync("Navigation")
  </aside>

  <section class="WikiPage">
	  @RenderBody()
  </section>


 <style>
	html 
	{
		font-family: Arial;
		font-size: 16px;
		background: white;
		
	}
	.sidebar
	{
		position: fixed;
		width: 25%;
		min-height: 100vh;
		height: 100vh;
		max-height: 100vh;
		background: #312450;
		font-size: 0.65em;
		overflow-y: auto;
	}
	 /* Hide scrollbar for Chrome, Safari and Opera */
	.sidebar::-webkit-scrollbar {
		display: none;
	}

	/* Hide scrollbar for IE, Edge and Firefox */
	.sidebar {
		-ms-overflow-style: none;  /* IE and Edge */
		scrollbar-width: none;  /* Firefox */
	} 
	
 	.WikiPage 
	{
		position: relative;
		width: 75%;
		float: right;
		height: 100vh;
	}
	

	
	@@media only screen and (max-width: 1000px) 
	{
	
		.nav ul li a {
            font-size: 1.1em;
        }
		.nav ul ul a {
            font-size: 0.8em !important;
			padding-left: 25px !important;
        }

        .nav ul ul ul a {
            font-size: 0.65em !important;
			padding-left: 40px !important;
        }
		
	}
	@@media only screen and (max-width: 800px) 
	{
	
		.nav ul li a {
            font-size: .6em;
        }
		.nav ul ul a {
            font-size: 0.5em !important;
			padding-left: 15px !important;
        }

        .nav ul ul ul a {
            font-size: 0.4em !important;
			padding-left: 30px !important;
        }
		
	}

	@@media only screen and (max-width: 450px) 
	{
	
		.sidebar
		{
			height: 120vh;
		}
		.contentbody
		{
			font-size: .6em;
		}
		.nav ul li a {
            font-size: .55em;
        }
		.nav ul ul a {
			font-size: 0.35em !important;
            padding-left: 10px !important;
        }

        .nav ul ul ul a {
            padding-left: 15px !important;
			font-size: 0.4em !important;
        }
		
	}
 </style>
</main>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</html>